id: A64E2FDF4
title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
  of Suffering, the Secret Practice of the Great Compassionate One'
type: translation
pechas:
- I435438CC
- I14907914
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:09.527580
  last_modified_at: 2023-01-04 11:39:09.527587
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I435438CC/DA68: D5D7
  I14907914/4947: D5D7
